services:
  server: 
    build:
      context: .
      dockerfile: ./server/Dockerfile
      target: development
    image: server-image
    command: npm run dev
    env_file:
      - ./server/.env
    ports:
      - 3000:3000
    depends_on:
      - mongo
  client: 
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: development
    image: client-image
    command: npm run dev
    env_file:
      - ./client/.env
    ports:
      - 5173:5173
    depends_on:
      - server
  mongo:
    image: mongo